// Code generated by Kitex v0.11.3. DO NOT EDIT.

package stservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	server0 "github.com/cloudwego/kitex/pkg/generic/json_test/kitex_gen/kitex/test/server"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"testGeneric": kitex.NewMethodInfo(
		testGenericHandler,
		newSTServiceTestGenericArgs,
		newSTServiceTestGenericResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	sTServiceServiceInfo                = NewServiceInfo()
	sTServiceServiceInfoForClient       = NewServiceInfoForClient()
	sTServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return sTServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return sTServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return sTServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "STService"
	handlerType := (*server0.STService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "server",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func testGenericHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*server0.STServiceTestGenericArgs)
	realResult := result.(*server0.STServiceTestGenericResult)
	success, err := handler.(server0.STService).TestGeneric(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSTServiceTestGenericArgs() interface{} {
	return server0.NewSTServiceTestGenericArgs()
}

func newSTServiceTestGenericResult() interface{} {
	return server0.NewSTServiceTestGenericResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) TestGeneric(ctx context.Context, req *server0.GenericRequest) (r *server0.GenericResponse, err error) {
	var _args server0.STServiceTestGenericArgs
	_args.Req = req
	var _result server0.STServiceTestGenericResult
	if err = p.c.Call(ctx, "testGeneric", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
